#!/usr/bin/env bash
# forge-uki.sh — Quay UKI Builder
# Fuses vmlinuz + initramfs + cmdline into a signed or unsigned quay.efi
# Usage: forge-uki.sh <storage_uuid> [vfio_ids] [iso_cores] [--sign]
set -euo pipefail

STORAGE_UUID="$1"
VFIO_IDS="${2:-}"
ISO_CORES="${3:-}"
SIGN=false
[[ "${4:-}" == "--sign" ]] && SIGN=true

SB_DIR="/mnt/storage/secureboot"

# ── Dependencies ──────────────────────────────────────────────────────────────

# Prefer systemd-boot for the EFI stub; fall back to systemd-efistub (older naming)
apk add --quiet binutils systemd-boot 2>/dev/null \
    || apk add --quiet binutils systemd-efistub 2>/dev/null \
    || { echo "[!] Cannot install EFI stub package"; exit 1; }

$SIGN && apk add --quiet sbsigntools openssl efitools

# ── Locate build artefacts ────────────────────────────────────────────────────

STUB=$(find /usr/lib -name "linuxx64.efi.stub" 2>/dev/null | head -1)
[[ -z "$STUB" ]] && { echo "[!] linuxx64.efi.stub not found. Is systemd-boot installed?"; exit 1; }

KERNEL=$(ls /boot/vmlinuz-* 2>/dev/null | head -1)
INITRD=$(ls /boot/initramfs-* 2>/dev/null | head -1)
[[ -z "$KERNEL" ]] && { echo "[!] No vmlinuz found in /boot/"; exit 1; }
[[ -z "$INITRD" ]] && { echo "[!] No initramfs found in /boot/"; exit 1; }

# ── Cmdline assembly ──────────────────────────────────────────────────────────

CMDLINE="modules=loop,squashfs,sd-mod,usb-storage,ext4"
CMDLINE+=" alpine_dev=UUID=${STORAGE_UUID}"
CMDLINE+=" copytoram=yes quiet"

# 2MB hugepages are universally supported; 1GB require pdpe1gb CPU flag and
# silently do nothing on CPUs that lack it, causing confusing QEMU failures.
CMDLINE+=" hugepagesz=2M default_hugepagesz=2M"

# mitigations=auto without nosmt — nosmt halves CPU count by disabling HT,
# directly undercutting the isolcpus/VM-cores design.
CMDLINE+=" mitigations=auto"

if grep -qi "AuthenticAMD" /proc/cpuinfo; then
    CMDLINE+=" amd_iommu=on iommu=pt kvm_amd.nested=1"
else
    CMDLINE+=" intel_iommu=on iommu=pt kvm_intel.nested=1"
fi

[[ -n "$ISO_CORES" ]] && CMDLINE+=" isolcpus=$ISO_CORES nohz_full=$ISO_CORES rcu_nocbs=$ISO_CORES"
[[ -n "$VFIO_IDS"  ]] && CMDLINE+=" vfio-pci.ids=$VFIO_IDS rd.driver.pre=vfio_pci"

# Modloop: copied to storage root by install.sh; Alpine initramfs will mount
# alpine_dev then find it at the root of that partition.
CMDLINE+=" modloop=/modloop-lts modloop_verify=no"

echo "[FORGE] Cmdline: $CMDLINE"
printf '%s' "$CMDLINE" > /tmp/quay-cmdline

# ── Section VMA layout ────────────────────────────────────────────────────────
#
# objcopy embeds sections into the PE stub. VMAs must not overlap — firmware
# uses them as load addresses. We calculate dynamically from actual file sizes,
# aligning each to a 4KB page boundary.
#
# Layout: .osrel → .cmdline → (gap) → .linux → (gap) → .initrd

align_4k() {
    local size=$1
    echo $(( (size + 0xFFF) & ~0xFFF ))
}

OSREL_SIZE=$(stat -c%s /etc/os-release)
CMDL_SIZE=$(stat -c%s /tmp/quay-cmdline)
KERN_SIZE=$(stat -c%s "$KERNEL")

VMA_OSREL=0x20000
VMA_CMDLINE=$(( VMA_OSREL   + $(align_4k $OSREL_SIZE) ))
# Large gap before kernel so metadata section growth never reaches it
VMA_LINUX=$(( VMA_CMDLINE   + $(align_4k $CMDL_SIZE)  + 0x100000 ))
VMA_INITRD=$(( VMA_LINUX    + $(align_4k $KERN_SIZE)  + 0x100000 ))

printf "[FORGE] Section VMAs: .osrel=0x%x .cmdline=0x%x .linux=0x%x .initrd=0x%x\n" \
    $VMA_OSREL $VMA_CMDLINE $VMA_LINUX $VMA_INITRD

# ── Fuse UKI ─────────────────────────────────────────────────────────────────

UNSIGNED_OUT="/tmp/quay.efi.unsigned"
FINAL_OUT="/tmp/quay.efi"

echo "[FORGE] Fusing UKI..."
objcopy \
    --add-section .osrel="/etc/os-release"   --change-section-vma .osrel=$VMA_OSREL \
    --add-section .cmdline="/tmp/quay-cmdline" --change-section-vma .cmdline=$VMA_CMDLINE \
    --add-section .linux="$KERNEL"           --change-section-vma .linux=$VMA_LINUX \
    --add-section .initrd="$INITRD"          --change-section-vma .initrd=$VMA_INITRD \
    "$STUB" "$UNSIGNED_OUT"

# ── Secure Boot signing ───────────────────────────────────────────────────────

if $SIGN; then
    echo "[FORGE] Secure Boot signing requested."
    mkdir -p "$SB_DIR"

    DB_KEY="$SB_DIR/db.key"
    DB_CRT="$SB_DIR/db.crt"

    # Generate db signing key if not already present.
    # The full PK/KEK/db chain is generated by install.sh; forge-uki.sh only
    # needs the db pair to sign the UKI.
    if [[ ! -f "$DB_KEY" ]] || [[ ! -f "$DB_CRT" ]]; then
        echo "[FORGE] No db key found at $SB_DIR — generating now."
        echo "[FORGE] Run install.sh with --secure-boot to enroll the full chain."
        openssl req -newkey rsa:4096 -nodes -keyout "$DB_KEY" \
            -new -x509 -sha256 -days 3650 \
            -subj "/CN=Quay Secure Boot db/" \
            -out "$DB_CRT" 2>/dev/null
        chmod 600 "$DB_KEY"
        echo "[FORGE] db key generated: $DB_CRT"
    fi

    echo "[FORGE] Signing UKI with db key..."
    sbsign \
        --key "$DB_KEY" \
        --cert "$DB_CRT" \
        --output "$FINAL_OUT" \
        "$UNSIGNED_OUT"

    echo "[FORGE] Verifying signature..."
    sbverify --cert "$DB_CRT" "$FINAL_OUT" \
        && echo "[FORGE] Signature verified OK." \
        || { echo "[!] Signature verification failed."; exit 1; }

    rm -f "$UNSIGNED_OUT"
else
    mv "$UNSIGNED_OUT" "$FINAL_OUT"
    echo "[FORGE] UKI is unsigned. Secure Boot will reject this if enabled."
fi

echo "[FORGE] quay.efi ready: $(stat -c%s $FINAL_OUT) bytes"
